import os
from typing import Optional

import ujson
from kerchunk.hdf import SingleHdf5ToZarr
from fsspec.spec import AbstractFileSystem


# Note: default_fill_cache=False avoids caching data in between file
# chunks to lower memory usage.
DEFAULT_OPEN_KWARGS = dict(
    mode='rb',
    default_fill_cache=False,
    default_cache_type='first'
)

def generate_json(
    file_url: str,
    fs_remote: AbstractFileSystem,
    fs_local: AbstractFileSystem,
    output_dir: str ='.',
    open_kwargs: Optional[dict] = None,
    **kwargs,
) -> None:
    """Generate and save a JSON reference file for a single HDF5 file.

    Args:
        file_url (str): Path of the  HDF5 or netCDF data file in URL
            format (e.g., as generated by fsspec).
        output_dir (str, optional): Directory to save the reference JSON
            file output to. Defaults to the working directory.
        fs_remote (AbstractFileSystem, optional): The remote
            file system, e.g., `fsspec.filesystem('file')`.
        fs_local (AbstractFileSystem, optional): The local file system,
            e.g., `fsspec.filesystem('file')`.
        open_kwargs (Optional[dict], optional): Additional keyword
            arguments for opening the remote file.
        **kwargs: Additional keywords passed to SingleHdf5ToZarr.

    """
    open_kwargs = {
        **DEFAULT_OPEN_KWARGS,
        **(open_kwargs or {}),
    }

    with fs_remote.open(file_url, **open_kwargs) as infile:

        h5chunks = SingleHdf5ToZarr(infile, file_url, **kwargs)

        # Reference file names are the same as the data file but with
        # .json extension.
        basename = os.path.splitext(os.path.basename(file_url))[0]
        out_file = os.path.join(output_dir, f"{basename}.json")

        # Write the JSON reference file to the local file system.
        with fs_local.open(out_file, 'wb') as f:
            f.write(ujson.dumps(h5chunks.translate()).encode())
